language: php
php: '5.4'

env:
  global:
  - secure: OThtADsC34C6hN97+So9hBcjHtvJVrIUIwRdzFzS04brDwMjGP1MBqQ6ZN8getG5AxaJ8tvhc+dO/I4g2tl1zLlHIJfcpwO7e0Zi4YQeusjqTLKE4jW34yMyN9yPrB9pSNxRNGRLz/4BM7UBM5oZXyzM/YEFLAK36NV2qYhRCkLEu4zgn0mDthwXluJ7oDDRlK7Nx4gjVdrcH7mXcJyyy6o6yZBncCy9EIycVW5rmdNd8CmT0X+LbzDtiJqM0LDPsN++J0SkPNYqyZ9lKGn16B+0jN3oCWdk/xX0jQEfoY+dT8Y+Tfhk5koihzk+D8fv1LQQ98UfJlpqV1nmTePkEzVf5knkx9LIRkDE/IzQZirl3exdYU7iYzCdAsDh5Y/G8SnYY5lEleO9z8roMD0HsKl4pqQoJQzbJmT7MHQbIITyOMVF/XlkQX0u5ZjktNu8Ky2xhDksxmy1qEsxPn5uCuLe8YbCSjEYuKnFci9Rf1z7o0cQBQpEWZW36a8ZOKuL4P5x+oP71cy11RljkRFDdgsvwrkVh3rqsU9RjNaD3i1o/68wv4p/r7pNnTcYZybXDekjxE83MQ4mbAjj+Yq6H57CES22EyxwjIIQvNKgxPjy9y3UczU/NcQTia50Sil3q4vEDf9olijktMpcE7aLF/C0iSBtqUuoxOlmsCs2n30=
  - secure: OTBDEiyFH6d5JlEYpj6o+qSYVt1PDbgOjJMcdrqWTipuRzQMlEmudPINePIvGjdtbL6Z8qXDOzEs9R1I8KG0B6p4XtHxAJ+yd2BnygVSk39EmQN6vZ5Wuc1TVJEdjnytFGBTKZMVoybE3eUOR6zBhvbQpbibFxuRO6fZq9S7HF+eJU8d9VQnoUdmS8IgvyvC5r0dXwBZV6UuaL1tPnSexjQGmVYaphdIuL4MBo0TzZVGmFuqFaKgHAzMW7mO/cLHAgdLraWgtMrVEXj9mijOySOeqozY42yXzQ9zBeiRV14WKaB6KEGuwniDxD6XdT4zEz7wXPVGHBt49d7blwIEsQAKc7uGyQGydJDU55tjgRpmh6J71XZ0zfmNA5z6mwGtZGPBdyQO1U+JztJGXM0i1V6FXP605bVP+xg66KQboCTTIxIsTPhOf8lj/zg4rE80w9+b3hMBTjbHYjZVPVZgba3koRoCBOt7u4LsMP3J7Gt0GYL0AHwCdaXiS65N8ufTdfQPpZgtLR3f6lm+QgxvQ3w5OxlclKRCRpa1CdNS+8w8XeTRfXIGUawr0UcCIct3egjPP6JT/pIq+HX0bK7L4QIvWNahFU3vfYGYWEDz5N+WQAVcy9GSLt3XCZQJEJnD4S8c0hoALq6iZPlxjmwCWfCrrAjE+F40Y/JJ86mrIo4=

script: phpunit Test.php

before_deploy:
  - npm install gulp
  - npm install gulp -g
  - npm install vinyl-ftp gulp-util minimist --save-dev
  
deploy:
  skip_cleanup: true
  provider: script
#  script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gulp deploy --user $FTP_USER --password $FTP_PASSWORD; fi
  script: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
  on:
    tags: true

